# Generated by Django 5.1.5 on 2025-01-24 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0003_remove_post_image_post_banner_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MaxValueValidator(999999.99)]),
        ),
    ]
