# Generated by Django 5.1.5 on 2025-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0004_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='sans nom', max_length=150),
        ),
    ]
