# Generated by Django 5.1.5 on 2025-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0006_remove_post_name_post_author_post_title_postvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='../media/default.jpeg', upload_to='profile_images'),
        ),
    ]
