# Generated by Django 5.1.5 on 2025-01-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0008_profile_banner_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='sans email', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='sans password', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
