# Generated by Django 4.2.23 on 2025-07-30 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinetPayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_country', models.CharField(max_length=2)),
                ('customer_state', models.CharField(max_length=2)),
                ('customer_zip_code', models.CharField(max_length=10)),
                ('seller_phone_number', models.CharField(max_length=20)),
                ('seller_country', models.CharField(max_length=2)),
                ('seller_operator', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('payment_received', 'Paiement reçu'), ('in_escrow', 'En séquestre'), ('escrow_released', 'Séquestre libéré'), ('escrow_refunded', 'Séquestre remboursé'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending_payment', max_length=20)),
                ('cinetpay_transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_released_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_transaction', to='blizzgame.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_escrow', 'En séquestre'), ('released', 'Libéré'), ('refunded', 'Remboursé')], default='in_escrow', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cinetpay_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='blizzgame.cinetpaytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_country', models.CharField(max_length=2)),
                ('recipient_operator', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('cinetpay_payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='blizzgame.escrowtransaction')),
            ],
        ),
    ]
