# Generated by Django 4.2.23 on 2025-07-30 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blizzgame', '0012_cinetpaytransaction_escrowtransaction_payoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('preferred_payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement Bancaire'), ('card', 'Carte Bancaire')], default='mobile_money', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('operator', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('free_money', 'Free Money'), ('emoney', 'E-Money'), ('airtel_money', 'Airtel Money')], max_length=20, null=True)),
                ('country', models.CharField(default='SN', max_length=2)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
