# Generated by Django 4.2.23 on 2025-07-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0013_sellerpaymentinfo'),
    ]

    operations = [
    ]
