# Generated by Django 4.2.23 on 2025-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0014_auto_20250730_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_game_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='game_type',
            field=models.CharField(choices=[('FreeFire', 'FreeFire'), ('PUBG', 'PUBG Mobile'), ('COD', 'Call of Duty Mobile'), ('efootball', 'eFootball Mobile'), ('fc25', 'FC25 Mobile'), ('bloodstrike', 'Bloodstrike'), ('other', 'Autre')], default='other', max_length=50),
        ),
    ]
