# Generated by Django 4.2.23 on 2025-08-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0015_post_custom_game_name_post_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coins',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
    ]
