# Generated by Django 4.2.23 on 2025-08-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0017_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coins',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
    ]
