# Generated by Django 4.2.23 on 2025-08-05 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blizzgame', '0018_update_coins_level_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_total_transactions', models.IntegerField(default=0)),
                ('seller_successful_transactions', models.IntegerField(default=0)),
                ('seller_failed_transactions', models.IntegerField(default=0)),
                ('seller_fraudulent_transactions', models.IntegerField(default=0)),
                ('seller_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('seller_badge', models.CharField(default='novice', max_length=50)),
                ('buyer_total_transactions', models.IntegerField(default=0)),
                ('buyer_successful_transactions', models.IntegerField(default=0)),
                ('buyer_failed_transactions', models.IntegerField(default=0)),
                ('buyer_disputed_transactions', models.IntegerField(default=0)),
                ('buyer_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('buyer_badge', models.CharField(default='novice', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating_type', models.CharField(choices=[('seller', 'Vendeur'), ('buyer', 'Acheteur')], max_length=10)),
                ('outcome', models.CharField(choices=[('success', 'Réussi'), ('failed', 'Échoué'), ('disputed', 'Litigieux'), ('fraudulent', 'Frauduleux')], max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blizzgame.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'transaction', 'rating_type')},
            },
        ),
    ]
