# Generated by Django 4.2.23 on 2025-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0019_add_rating_badge_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_games',
            field=models.JSONField(blank=True, default=list, help_text="Liste des jeux favoris de l'utilisateur"),
        ),
    ]
