# Generated by Django 5.2.5 on 2025-08-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0023_shopifyintegration_cart_order_productcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='group_message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='private_message',
        ),
    ]
